"use client";
import {useEffect,useState} from "react";
import {CapacityLevel,Domain,LoadSettings,TaskItem,completeRecurringTask,loadCustomWorkspaces,loadDailyCapacity,loadDomainState,localDateKey,recurringComplete,recurringProgress,saveCustomWorkspace,saveDailyCapacity,saveDomainState,taskPoints} from "@/lib/storage";
import {actionsOf,replaceActions} from "@/lib/actions";
import {buildDailyProposal,buildDownProposal,PlannerSource} from "@/lib/planner";
import {workspaceColor} from "@/lib/workspaceColors";
type Ref=PlannerSource&{key:string;label:string;sub?:string;source:{kind:"custom";id:string}|{kind:"domain";domain:Domain};task:TaskItem;order:number;color:string};
type ModeWorkspace={mode?:"standard"|"sport"};
const LEVELS:[[CapacityLevel,string],[CapacityLevel,string],[CapacityLevel,string]]=[["low","Basse"],["normal","Normale"],["high","Haute"]];
const LOAD_LABEL={light:"Basse",normal:"Moyenne",heavy:"Lourde"} as const;
const loadLabel=(task:TaskItem)=>LOAD_LABEL[task.effort??"normal"];
const recurringLabel=(task:TaskItem)=>task.recurringTarget?` · ${recurringProgress(task).count}/${recurringProgress(task).target} cette semaine`:"";
export default function DailyPlan({down,settings,onCapacity}:{down:boolean;settings:LoadSettings;onCapacity?:(l:CapacityLevel)=>void}){
 const[version,setVersion]=useState(0),[capacity,setCapacity]=useState<CapacityLevel|null>(null),[editing,setEditing]=useState(false),[draft,setDraft]=useState<string[]>([]);const today=localDateKey();
 useEffect(()=>setCapacity(loadDailyCapacity()?.level??null),[version]);
 const refs=(()=>{if(typeof window==="undefined")return[] as Ref[];const out:Ref[]=[];for(const w of loadCustomWorkspaces()){if((w as typeof w&ModeWorkspace).mode==="sport")continue;const color=workspaceColor(w);actionsOf(w.state).forEach((task,order)=>{if(task.done||task.waiting||recurringComplete(task))return;const project=w.state.projects.find(x=>x.id===task.projectId);out.push({key:`c:${w.id}:${task.id}`,label:w.name,sub:project?.name,source:{kind:"custom",id:w.id},task,project,order,color})})}const life=loadDomainState("vie");actionsOf(life).forEach((task,order)=>{if(task.done||task.waiting||recurringComplete(task))return;const project=life.projects.find(x=>x.id===task.projectId);out.push({key:`d:vie:${task.id}`,label:"Vie",sub:project?.name,source:{kind:"domain",domain:"vie"},task,project,order,color:"#2DD4BF"})});return out})();
 const todayRefs=refs.filter(r=>r.task.todayDate===today);
 const proposalFor=(level:CapacityLevel)=>down?buildDownProposal(refs,settings,today) as Ref[]:buildDailyProposal(refs,level,settings,today) as Ref[];
 const proposalWithOverrides=(level:CapacityLevel)=>{const keys=new Set(proposalFor(level).map(r=>r.key));for(const r of refs){if(r.task.capacityOverrideDate!==today)continue;if(r.task.todayDate===today)keys.add(r.key);else keys.delete(r.key)}return refs.filter(r=>keys.has(r.key))};
 const saveToday=(keys:string[],manual=false,baselineKeys:string[]=[])=>{const set=new Set(keys),baseline=new Set(baselineKeys);const update=(keyFor:(t:TaskItem)=>string,t:TaskItem)=>{const key=keyFor(t),selected=set.has(key),wasToday=t.todayDate===today;let capacityOverrideDate=t.capacityOverrideDate;if(manual){const differs=selected!==baseline.has(key);capacityOverrideDate=differs?today:capacityOverrideDate===today?undefined:capacityOverrideDate}return{...t,todayDate:selected?today:wasToday?undefined:t.todayDate,capacityOverrideDate}};for(const w of loadCustomWorkspaces()){if((w as typeof w&ModeWorkspace).mode==="sport")continue;saveCustomWorkspace(w.id,replaceActions(w.state,actionsOf(w.state).map(t=>update(x=>`c:${w.id}:${x.id}`,t))))}const life=loadDomainState("vie");saveDomainState("vie",replaceActions(life,actionsOf(life).map(t=>update(x=>`d:vie:${x.id}`,t))));setEditing(false);setVersion(v=>v+1)};
 const chooseCapacity=(l:CapacityLevel)=>{const hadProgram=todayRefs.length>0||refs.some(r=>r.task.capacityOverrideDate===today);saveDailyCapacity(l);setCapacity(l);onCapacity?.(l);setDraft([]);if(hadProgram)saveToday(proposalWithOverrides(l).map(r=>r.key))};
 const proposal=capacity?proposalWithOverrides(capacity):[];
 const levelButtons=<div className="flex gap-1">{LEVELS.map(([v,l])=><button key={v} onClick={()=>chooseCapacity(v)} className={`rounded-md border px-3 py-1.5 text-xs ${capacity===v?"border-teal/60 bg-teal/10 text-teal":"border-white/15 text-muted hover:border-teal/40 hover:text-ink"}`}>{l}</button>)}</div>;
 const done=(r:Ref)=>{const recurring=!!r.task.recurringTarget;const finish=(t:TaskItem)=>t.id===r.task.id?(recurring?completeRecurringTask(t,today):{...t,done:true,todayDate:undefined,capacityOverrideDate:undefined}):t;const completionId=recurring?`${r.task.id}:${today}:${(r.task.recurringCount??0)+1}`:r.task.id;const addCompletion=<T extends {completedThisWeek?:{id:string;text:string;date:string;kind?:"priority"|"task"}[]}>(state:T)=>state.completedThisWeek?.some(t=>t.id===completionId)?state:{...state,completedThisWeek:[...(state.completedThisWeek??[]),{id:completionId,text:r.task.text,date:today,kind:"priority" as const}]};if(r.source.kind==="custom"){const workspaceId=r.source.id,w=loadCustomWorkspaces().find(x=>x.id===workspaceId);if(w){const updated=replaceActions(w.state,actionsOf(w.state).map(finish));saveCustomWorkspace(w.id,addCompletion(updated))}}else{const domain=r.source.domain,state=loadDomainState(domain);const updated=replaceActions(state,actionsOf(state).map(finish));saveDomainState(domain,addCompletion(updated))}setVersion(v=>v+1)};
 if(!capacity)return <section className="rounded-xl border border-white/10 bg-panel px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm"><span className="text-teal font-medium">IBES</span> · Ta capacité aujourd’hui ?</p>{levelButtons}</div></section>;
 if(todayRefs.length===0&&refs.length>0){const proposedKeys=proposal.map(r=>r.key);return <section className="rounded-xl border border-teal/25 bg-teal/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-[10px] font-mono uppercase tracking-widest text-teal">IBES · Programme proposé</p>{levelButtons}</div><div className="mt-3 space-y-2">{(editing?refs:proposal).map(r=>{const selected=editing?(draft.length?draft.includes(r.key):proposedKeys.includes(r.key)):true;return <button key={r.key} disabled={!editing} onClick={()=>setDraft(d=>{const cur=d.length?d:proposedKeys;return cur.includes(r.key)?cur.filter(x=>x!==r.key):[...cur,r.key]})} className={`w-full text-left rounded-lg border px-4 py-3 ${selected?"bg-panel":"border-white/5 opacity-45"}`} style={selected?{borderColor:`${r.color}66`}:undefined}><span className="flex items-center gap-2 text-sm"><span className="h-2 w-2 rounded-full shrink-0" style={{backgroundColor:r.color}}/>{r.task.text}</span><span className="ml-4 text-[10px]" style={{color:r.color}}>{r.label}{r.sub?` · ${r.sub}`:""} · {loadLabel(r.task)}{recurringLabel(r.task)}</span></button>})}{proposal.length===0&&<p className="text-sm text-muted">Aucune action ne rentre proprement dans cette capacité.</p>}</div><div className="mt-4 flex gap-3 justify-end">{editing?<><button onClick={()=>{setEditing(false);setDraft([])}} className="text-xs text-muted">Annuler</button><button onClick={()=>saveToday(draft.length?draft:proposedKeys,true,proposedKeys)} className="rounded-md bg-teal px-4 py-2 text-xs text-graphite">Valider</button></>:<><button onClick={()=>{setDraft(proposedKeys);setEditing(true)}} className="text-xs text-muted">Modifier</button><button onClick={()=>saveToday(proposedKeys)} className="rounded-md bg-teal px-4 py-2 text-xs text-graphite">Accepter</button></>}</div></section>}
 if(todayRefs.length===0)return null;
 const visible=down?buildDownProposal(todayRefs,settings,today) as Ref[]:todayRefs;const total=visible.reduce((n,r)=>n+taskPoints(r.task,settings),0),maxLoad=Math.max(settings.highCapacity,1),loadRatio=Math.min(1,total/maxLoad),loadSegments=total===0?0:Math.max(1,Math.ceil(loadRatio*5)),chargeLabel=loadRatio<=.25?"Légère":loadRatio<=.5?"Modérée":loadRatio<=.75?"Soutenue":"Intense";
 return <section className="rounded-2xl border border-white/10 bg-panel p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-widest text-muted">Aujourd’hui</p><p className="mt-1 font-display text-2xl text-amber">Charge {chargeLabel.toLowerCase()}</p><div className="mt-2 flex w-36 gap-1" aria-label={`Charge ${chargeLabel.toLowerCase()}`}>{[0,1,2,3,4].map(i=><span key={i} className={`h-1.5 flex-1 rounded-full ${i<loadSegments?"bg-amber":"bg-white/10"}`}/>)}</div></div><div className="flex flex-wrap items-center gap-4">{levelButtons}</div></div>{down&&visible.length<todayRefs.length&&<p className="text-xs text-alert mt-3">DOWN masque {todayRefs.length-visible.length} élément{todayRefs.length-visible.length>1?"s":""} pour protéger la journée.</p>}<div className="mt-5 space-y-2">{visible.map((r,i)=><div key={r.key} className="flex items-center gap-3 rounded-lg border px-4 py-3" style={{borderColor:`${r.color}66`}}><button onClick={()=>done(r)} className="w-5 h-5 rounded border border-teal/50 text-transparent hover:text-teal">✓</button><span className="font-mono text-xs text-muted">{String(i+1).padStart(2,"0")}</span><span className="h-2.5 w-2.5 rounded-full shrink-0" style={{backgroundColor:r.color}}/><div className="flex-1"><p className="text-sm">{r.task.text}</p><p className="text-[10px]" style={{color:r.color}}>{r.label}{r.sub?` · ${r.sub}`:""} · {loadLabel(r.task)}{recurringLabel(r.task)}</p></div></div>)}</div><button onClick={()=>saveToday([])} className="mt-4 text-[10px] font-mono uppercase text-muted">Effacer le programme du jour</button></section>;
}
