"use client";
import {useEffect,useMemo,useState} from "react";
import {CapacityLevel,LoadSettings,Project,TaskItem,loadCustomWorkspaces,loadDailyCapacity,localDateKey,saveCustomWorkspace,saveDailyCapacity,taskPoints} from "@/lib/storage";
import {actionsOf,replaceActions} from "@/lib/actions";
import {buildDailyProposal,PlannerSource} from "@/lib/planner";
type Ref=PlannerSource&{key:string;label:string;sub?:string;workspaceId:string;task:TaskItem;project?:Project;projectDue?:string;order:number};
const LEVELS:[[CapacityLevel,string],[CapacityLevel,string],[CapacityLevel,string]]=[["low","Basse"],["normal","Normale"],["high","Haute"]];
const LOAD_LABEL={light:"Basse",normal:"Moyenne",heavy:"Lourde"} as const;
const PROJECT_COLORS=["#2DD4BF","#F59E0B","#60A5FA","#A78BFA","#F472B6","#FB7185","#34D399","#F97316"] as const;
type ColoredProject=Project&{color?:string};
const loadLabel=(task:TaskItem)=>LOAD_LABEL[task.effort??"normal"];
function projectColor(p?:Project){if(!p)return undefined;const color=(p as ColoredProject).color;if(color&&/^#[0-9a-f]{6}$/i.test(color))return color;let hash=0;for(let i=0;i<p.id.length;i++)hash=(hash*31+p.id.charCodeAt(i))>>>0;return PROJECT_COLORS[hash%PROJECT_COLORS.length];}
export default function DailyPlan({down,settings,onCapacity}:{down:boolean;settings:LoadSettings;onCapacity?:(l:CapacityLevel)=>void}){
 const[version,setVersion]=useState(0),[capacity,setCapacity]=useState<CapacityLevel|null>(null),[editing,setEditing]=useState(false),[draft,setDraft]=useState<string[]>([]);const today=localDateKey();
 useEffect(()=>setCapacity(loadDailyCapacity()?.level??null),[version]);
 const refs=useMemo(()=>{if(typeof window==="undefined")return[] as Ref[];const out:Ref[]=[];for(const w of loadCustomWorkspaces()){actionsOf(w.state).forEach((task,order)=>{if(task.done||task.waiting)return;const p=w.state.projects.find(x=>x.id===task.projectId);out.push({key:`c:${w.id}:${task.id}`,label:w.name,sub:p?.name,workspaceId:w.id,task,project:p,projectDue:p?.dueDate,order})})}return out},[version,today]);
 const todayRefs=refs.filter(r=>r.task.todayDate===today);
 const proposalFor=(level:CapacityLevel)=>buildDailyProposal(refs,level,settings,today) as Ref[];
 const saveToday=(keys:string[])=>{const set=new Set(keys);for(const w of loadCustomWorkspaces())saveCustomWorkspace(w.id,replaceActions(w.state,actionsOf(w.state).map(t=>({...t,todayDate:set.has(`c:${w.id}:${t.id}`)?today:t.todayDate===today?undefined:t.todayDate}))));setEditing(false);setVersion(v=>v+1)};
 const chooseCapacity=(l:CapacityLevel)=>{const hadProgram=todayRefs.length>0;saveDailyCapacity(l);setCapacity(l);onCapacity?.(l);setDraft([]);if(hadProgram)saveToday(proposalFor(l).map(r=>r.key))};
 const proposal=useMemo(()=>capacity?proposalFor(capacity):[],[refs,capacity,settings,today]);
 const levelButtons=<div className="flex gap-1">{LEVELS.map(([v,l])=><button key={v} onClick={()=>chooseCapacity(v)} className={`rounded-md border px-3 py-1.5 text-xs ${capacity===v?"border-teal/60 bg-teal/10 text-teal":"border-white/15 text-muted hover:border-teal/40 hover:text-ink"}`}>{l}</button>)}</div>;
 const done=(r:Ref)=>{const w=loadCustomWorkspaces().find(x=>x.id===r.workspaceId);if(w)saveCustomWorkspace(w.id,replaceActions(w.state,actionsOf(w.state).map(t=>t.id===r.task.id?{...t,done:true,todayDate:undefined}:t)));setVersion(v=>v+1)};
 if(!capacity)return <section className="rounded-xl border border-white/10 bg-panel px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm"><span className="text-teal font-medium">IBES</span> · Ta capacité aujourd’hui ?</p>{levelButtons}</div></section>;
 if(todayRefs.length===0&&refs.length>0){const proposedKeys=proposal.map(r=>r.key);return <section className="rounded-xl border border-teal/25 bg-teal/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-[10px] font-mono uppercase tracking-widest text-teal">IBES · Programme proposé</p>{levelButtons}</div><div className="mt-3 space-y-2">{(editing?refs:proposal).map(r=>{const selected=editing?(draft.length?draft.includes(r.key):proposedKeys.includes(r.key)):true,color=projectColor(r.project);return <button key={r.key} disabled={!editing} onClick={()=>setDraft(d=>{const cur=d.length?d:proposedKeys;return cur.includes(r.key)?cur.filter(x=>x!==r.key):[...cur,r.key]})} className={`w-full text-left rounded-lg border px-4 py-3 ${selected?"bg-panel":"border-white/5 opacity-45"}`} style={selected&&color?{borderColor:`${color}66`}:undefined}><span className="flex items-center gap-2 text-sm">{color&&<span className="h-2 w-2 rounded-full shrink-0" style={{backgroundColor:color}}/>}{r.task.text}</span><span className="ml-4 text-[10px]" style={color?{color}:undefined}>{r.label}{r.sub?` · ${r.sub}`:""} · {loadLabel(r.task)}</span></button>})}{proposal.length===0&&<p className="text-sm text-muted">Aucune action ne rentre proprement dans cette capacité.</p>}</div><div className="mt-4 flex gap-3 justify-end">{editing?<><button onClick={()=>{setEditing(false);setDraft([])}} className="text-xs text-muted">Annuler</button><button onClick={()=>saveToday(draft.length?draft:proposedKeys)} className="rounded-md bg-teal px-4 py-2 text-xs text-graphite">Valider</button></>:<><button onClick={()=>{setDraft(proposedKeys);setEditing(true)}} className="text-xs text-muted">Modifier</button><button onClick={()=>saveToday(proposedKeys)} className="rounded-md bg-teal px-4 py-2 text-xs text-graphite">Accepter</button></>}</div></section>}
 if(todayRefs.length===0)return null;
 const total=todayRefs.reduce((n,r)=>n+taskPoints(r.task,settings),0),maxLoad=Math.max(settings.highCapacity,1),loadRatio=Math.min(1,total/maxLoad),loadSegments=total===0?0:Math.max(1,Math.ceil(loadRatio*5)),chargeLabel=loadRatio<=.25?"Légère":loadRatio<=.5?"Modérée":loadRatio<=.75?"Soutenue":"Intense";let used=0;const visible=down?todayRefs.filter(r=>{const p=taskPoints(r.task,settings);if(used+p>settings.lowCapacity&&used>0)return false;used+=p;return true}):todayRefs;
 return <section className="rounded-2xl border border-white/10 bg-panel p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-widest text-muted">Aujourd’hui</p><p className="mt-1 font-display text-2xl text-amber">Charge {chargeLabel.toLowerCase()}</p><div className="mt-2 flex w-36 gap-1" aria-label={`Charge ${chargeLabel.toLowerCase()}`}>{[0,1,2,3,4].map(i=><span key={i} className={`h-1.5 flex-1 rounded-full ${i<loadSegments?"bg-amber":"bg-white/10"}`}/>)}</div></div><div className="flex flex-wrap items-center gap-4">{levelButtons}</div></div>{down&&visible.length<todayRefs.length&&<p className="text-xs text-alert mt-3">DOWN masque {todayRefs.length-visible.length} élément{todayRefs.length-visible.length>1?"s":""} pour protéger la journée.</p>}<div className="mt-5 space-y-2">{visible.map((r,i)=>{const color=projectColor(r.project);return <div key={r.key} className="flex items-center gap-3 rounded-lg border px-4 py-3" style={color?{borderColor:`${color}66`}:undefined}><button onClick={()=>done(r)} className="w-5 h-5 rounded border border-teal/50 text-transparent hover:text-teal">✓</button><span className="font-mono text-xs text-muted">{String(i+1).padStart(2,"0")}</span>{color&&<span className="h-2.5 w-2.5 rounded-full shrink-0" style={{backgroundColor:color}}/>}<div className="flex-1"><p className="text-sm">{r.task.text}</p><p className="text-[10px]" style={color?{color}:undefined}>{r.label}{r.sub?` · ${r.sub}`:""} · {loadLabel(r.task)}</p></div></div>})}</div><button onClick={()=>saveToday([])} className="mt-4 text-[10px] font-mono uppercase text-muted">Effacer le programme du jour</button></section>;
}
