"use client";
import Link from "next/link";
import {CapacityLevel,Domain,DomainState,LoadSettings,capacityValue,effortMultiplier,localDateKey} from "@/lib/storage";

type Props={states:Record<Domain,DomainState>;capacity:CapacityLevel|null;settings:LoadSettings;onCapacity:(l:CapacityLevel)=>void};
const LABEL:Record<Domain,string>={musique:"Musique",esport:"Esport",vie:"Vie"};
export default function MorningBriefing({states,capacity,settings,onCapacity}:Props){
 const today=localDateKey();
 if(!capacity)return <section className="rounded-2xl border border-teal/30 bg-teal/5 p-6"><p className="text-[10px] font-mono uppercase tracking-[.25em] text-teal">Briefing IBES</p><h2 className="font-display text-2xl mt-2">Bonjour. Comment sont tes ressources aujourd'hui ?</h2><p className="text-sm text-muted mt-2">Donne-moi ta capacité et je te résume la journée.</p><div className="flex flex-wrap gap-2 mt-5">{([['low','Basse'],['normal','Normale'],['high','Haute']] as const).map(([v,l])=><button key={v} onClick={()=>onCapacity(v)} className="rounded-md border border-white/15 px-4 py-2 text-xs hover:border-teal/50">{l}</button>)}</div></section>;
 const domains=(['musique','esport','vie'] as Domain[]).map(domain=>{const s=states[domain],tasks=s.briefing.tasks.filter(t=>!t.done&&!t.waiting&&(!t.deferredUntil||t.deferredUntil<=today)),deadline=s.projects.filter(p=>!p.done&&p.dueDate&&p.dueDate>=today).sort((a,b)=>a.dueDate!.localeCompare(b.dueDate!))[0];return{domain,tasks,deadline,points:Math.round(tasks.reduce((n,t)=>n+settings.priorityWeight*effortMultiplier(t.effort),0))}});
 const totalTasks=domains.reduce((n,d)=>n+d.tasks.length,0),totalPoints=domains.reduce((n,d)=>n+d.points,0),cap=capacityValue(capacity,settings),heavy=domains.flatMap(d=>d.tasks.filter(t=>t.effort==='heavy').map(t=>({domain:d.domain,task:t}))),soon=domains.filter(d=>d.deadline&&Math.ceil((new Date(d.deadline.dueDate!+'T00:00:00').getTime()-new Date(today+'T00:00:00').getTime())/86400000)<=7);
 const ranked=domains.filter(d=>d.tasks.length).sort((a,b)=>{const ad=a.deadline?1:0,bd=b.deadline?1:0;return (bd*100+b.points)-(ad*100+a.points)}).slice(0,2);
 const overloaded=totalPoints>cap;
 return <section className="rounded-2xl border border-teal/25 bg-panel p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-[.25em] text-teal">Briefing IBES</p><h2 className="font-display text-2xl mt-2">Voilà la journée.</h2></div><span className={`text-[10px] font-mono uppercase rounded-full border px-3 py-1 ${capacity==='low'?'border-alert/30 text-alert':capacity==='high'?'border-teal/30 text-teal':'border-amber/30 text-amber'}`}>Capacité {capacity==='low'?'basse':capacity==='high'?'haute':'normale'}</span></div><div className="grid sm:grid-cols-3 gap-3 mt-6"><div className="rounded-lg border border-white/10 p-3"><p className="font-display text-2xl">{totalTasks}</p><p className="text-[10px] text-muted uppercase">priorités ouvertes</p></div><div className="rounded-lg border border-white/10 p-3"><p className="font-display text-2xl">{totalPoints}/{cap}</p><p className="text-[10px] text-muted uppercase">points / capacité</p></div><div className="rounded-lg border border-white/10 p-3"><p className="font-display text-2xl">{soon.length}</p><p className="text-[10px] text-muted uppercase">échéances ≤ 7 jours</p></div></div><div className="mt-6 space-y-2 text-sm">{overloaded&&<p><span className="text-alert">Charge trop haute.</span> Ta journée dépasse ta capacité actuelle.</p>}{capacity==='low'&&heavy.length>0&&<p><span className="text-amber">{heavy.length} priorité{heavy.length>1?'s':''} lourde{heavy.length>1?'s':''}</span> demande{heavy.length===1?'':'nt'} plus d'énergie que le reste.</p>}{soon.length>0&&<p><span className="text-cyan">Échéance proche :</span> {soon.map(d=>`${LABEL[d.domain]} · ${d.deadline!.name}`).join(' · ')}</p>}</div>{ranked.length>0&&<div className="mt-6 pt-5 border-t border-white/10"><p className="text-[10px] font-mono uppercase tracking-widest text-muted mb-3">Je protégerais surtout</p>{ranked.map(d=><div key={d.domain} className="flex items-start gap-3 py-2"><span className="text-teal">→</span><div><p className="font-medium">{LABEL[d.domain]}</p><p className="text-sm text-muted">{d.tasks[0]?.text}</p></div></div>)}</div>}<div className="mt-5 flex gap-4 text-xs"><Link href={ranked[0]?.domain==='musique'?'/musique':ranked[0]?.domain==='esport'?'/esport':'/'} className="text-teal">Ouvrir la priorité →</Link>{overloaded&&<span className="text-muted">Tu peux aussi passer en DOWN ou filtrer ta journée.</span>}</div></section>;
}
