"use client";
import { useState } from "react";
import { Project, TaskItem, localDateKey } from "@/lib/storage";

export default function ProjectsPanel({projects,tasks,onChange,onTasksChange}:{projects:Project[];tasks:TaskItem[];onChange:(p:Project[])=>void;onTasksChange?:(t:TaskItem[])=>void}){
 const [name,setName]=useState(""); const [goal,setGoal]=useState(""); const [dueDate,setDueDate]=useState(""); const [newActions,setNewActions]=useState<Record<string,string>>({}); const [creating,setCreating]=useState(false);
 const add=()=>{if(!name.trim())return;onChange([...projects,{id:crypto.randomUUID(),name:name.trim(),goal:goal.trim(),dueDate:dueDate||undefined,done:false}]);setName("");setGoal("");setDueDate("");setCreating(false);};
 const addAction=(projectId:string)=>{const text=(newActions[projectId]||"").trim();if(!text||!onTasksChange)return;onTasksChange([...tasks,{id:crypto.randomUUID(),text,done:false,effort:"normal",projectId}]);setNewActions(s=>({...s,[projectId]:""}));};
 const toggleAction=(id:string)=>{if(!onTasksChange)return;onTasksChange(tasks.map(t=>t.id===id?{...t,done:!t.done,todayDate:t.done?t.todayDate:undefined}:t));};
 const today=localDateKey();
 return <div className="space-y-8">
  <div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-[0.22em] text-muted">Pilotage</p><h2 className="font-display text-3xl mt-1">Projets</h2><p className="text-sm text-muted mt-2">Un aperçu clair de ce qui avance et de ce qu'il reste à faire.</p></div><button onClick={()=>setCreating(v=>!v)} className={`shrink-0 rounded-full border px-4 py-2 text-[11px] font-mono uppercase tracking-widest transition-colors ${creating?"border-white/15 text-muted":"border-amber/40 text-amber hover:bg-amber/5"}`}>{creating?"Fermer":"+ Nouveau"}</button></div>
  {creating&&<div className="rounded-2xl border border-amber/25 bg-panel p-5 space-y-4"><div><p className="text-[10px] font-mono uppercase tracking-widest text-amber">Nouveau projet</p><p className="text-xs text-muted mt-1">Nom, résultat attendu, échéance. Rien de plus.</p></div><div className="grid sm:grid-cols-2 gap-3"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Nom du projet" className="bg-graphite border border-white/10 rounded-lg px-4 py-3"/><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Résultat attendu" className="bg-graphite border border-white/10 rounded-lg px-4 py-3"/></div><div className="flex flex-col sm:flex-row gap-3"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="flex-1 bg-graphite border border-white/10 rounded-lg px-4 py-3 text-sm"/><button onClick={add} disabled={!name.trim()} className="rounded-lg bg-amber px-5 py-3 font-mono text-xs uppercase text-graphite disabled:opacity-40">Créer</button></div></div>}
  <div className="space-y-5">{projects.length===0&&<div className="rounded-2xl border border-dashed border-white/10 px-6 py-10 text-center"><p className="font-display text-xl text-muted">Aucun projet.</p><p className="text-sm text-muted mt-2">Crée seulement ce qui mérite vraiment d'être suivi.</p></div>}{projects.map(p=>{
    const linked=tasks.filter(t=>t.projectId===p.id),open=linked.filter(t=>!t.done),done=linked.filter(t=>t.done),due=p.dueDate?new Date(p.dueDate+"T00:00:00"):null,days=due?Math.ceil((due.getTime()-new Date(today+"T00:00:00").getTime())/86400000):null;
    const dueLabel=days===null?null:days<0?`${Math.abs(days)} j de retard`:days===0?"Aujourd'hui":days===1?"Demain":`Dans ${days} j`;
    return <article key={p.id} className={`rounded-2xl border bg-panel overflow-hidden transition-colors ${p.done?"border-white/5 opacity-60":"border-white/10 hover:border-white/20"}`}>
      <div className="p-5 sm:p-6"><div className="flex items-start gap-4"><button onClick={()=>onChange(projects.map(x=>x.id===p.id?{...x,done:!x.done}:x))} className={`mt-1 w-6 h-6 rounded-md border shrink-0 text-xs ${p.done?"border-teal/60 bg-teal/10 text-teal":"border-white/20 text-transparent hover:border-teal/50 hover:text-teal"}`}>✓</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`font-display text-2xl leading-none ${p.done?"line-through text-muted":""}`}>{p.name}</h3>{p.dueDate&&<span className={`rounded-full border px-2.5 py-1 text-[9px] font-mono uppercase tracking-wider ${days!==null&&days<=2?"border-alert/30 bg-alert/5 text-alert":"border-amber/25 bg-amber/5 text-amber"}`}>{dueLabel}</span>}</div>{p.goal&&<p className="text-sm text-muted mt-3 leading-relaxed max-w-2xl">{p.goal}</p>}<div className="flex flex-wrap gap-2 mt-4"><span className="rounded-full bg-graphite px-2.5 py-1 text-[10px] font-mono uppercase text-ink">{open.length} à faire</span>{done.length>0&&<span className="rounded-full bg-graphite/60 px-2.5 py-1 text-[10px] font-mono uppercase text-muted">{done.length} terminée{done.length>1?"s":""}</span>}{p.dueDate&&<span className="rounded-full bg-graphite/60 px-2.5 py-1 text-[10px] font-mono uppercase text-muted">{new Date(p.dueDate+"T00:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"short",year:"numeric"})}</span>}</div></div><button onClick={()=>onChange(projects.filter(x=>x.id!==p.id))} className="text-muted/60 hover:text-alert px-1">✕</button></div></div>
      <div className="border-t border-white/10 bg-graphite/20 px-5 sm:px-6 py-5"><div className="flex items-center justify-between gap-3 mb-3"><p className="text-[10px] font-mono uppercase tracking-[0.18em] text-muted">Actions</p>{open.length>0&&<span className="text-[10px] text-muted">{open.length} restante{open.length>1?"s":""}</span>}</div><div className="space-y-2">{open.length===0&&<p className="text-sm text-muted py-2">Aucune action ouverte.</p>}{open.map((t,i)=><div key={t.id} className="group flex items-center gap-3 rounded-xl border border-white/5 bg-panel/70 px-4 py-3.5"><button onClick={()=>toggleAction(t.id)} className="w-5 h-5 rounded border border-white/20 text-transparent hover:border-teal/60 hover:text-teal shrink-0">✓</button><span className="font-mono text-[10px] text-muted w-5">{String(i+1).padStart(2,"0")}</span><span className="flex-1 text-sm leading-snug">{t.text}</span><div className="flex items-center gap-2 shrink-0">{t.todayDate===today&&<span className="rounded-full border border-teal/25 px-2 py-1 text-[8px] font-mono uppercase text-teal">Aujourd'hui</span>}{t.waiting&&<span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-mono uppercase text-muted">Attente</span>}{t.dueDate&&<span className="text-[9px] font-mono text-amber">{new Date(t.dueDate+"T00:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}</span>}</div></div>)}</div>
      {done.length>0&&<details className="mt-3"><summary className="cursor-pointer text-[10px] font-mono uppercase tracking-widest text-muted hover:text-ink">{done.length} terminée{done.length>1?"s":""}</summary><div className="mt-2 space-y-1">{done.map(t=><button key={t.id} onClick={()=>toggleAction(t.id)} className="w-full flex items-center gap-3 rounded-lg px-4 py-2 text-left text-sm text-muted hover:bg-panel/60"><span className="text-teal">✓</span><span className="line-through flex-1">{t.text}</span><span className="text-[9px] font-mono uppercase">Réouvrir</span></button>)}</div></details>}
      {onTasksChange&&<div className="mt-4 flex gap-2"><input value={newActions[p.id]||""} onChange={e=>setNewActions(s=>({...s,[p.id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")addAction(p.id)}} placeholder="Ajouter une action…" className="min-w-0 flex-1 bg-transparent border-b border-white/10 px-1 py-2 text-sm focus:border-teal/40 outline-none"/><button onClick={()=>addAction(p.id)} disabled={!(newActions[p.id]||"").trim()} className="text-[10px] font-mono uppercase tracking-widest text-teal disabled:opacity-30">Ajouter</button></div>}</div>
    </article>
  })}</div>
 </div>;
}
