"use client";
import { useState } from "react";
import { EffortLevel, Project, TaskItem, localDateKey } from "@/lib/storage";

const EFFORT_LABEL:Record<EffortLevel,string>={light:"Basse",normal:"Normale",heavy:"Haute"};
const neutralBorder="rgba(255,255,255,.10)";

export default function ProjectsPanel({projects,tasks,accentColor,onChange,onTasksChange}:{projects:Project[];tasks:TaskItem[];accentColor:string;onChange:(p:Project[])=>void;onTasksChange?:(t:TaskItem[])=>void}){
 const[name,setName]=useState("");const[goal,setGoal]=useState("");const[dueDate,setDueDate]=useState("");const[newActions,setNewActions]=useState<Record<string,string>>({});const[creating,setCreating]=useState(false);const[menu,setMenu]=useState<string|null>(null);const[dragged,setDragged]=useState<string|null>(null);const[editingDate,setEditingDate]=useState<string|null>(null);const[editingActionDate,setEditingActionDate]=useState<string|null>(null);
 const add=()=>{if(!name.trim())return;onChange([...projects,{id:crypto.randomUUID(),name:name.trim(),goal:goal.trim(),dueDate:dueDate||undefined,done:false}]);setName("");setGoal("");setDueDate("");setCreating(false)};
 const addAction=(projectId:string)=>{const text=(newActions[projectId]||"").trim();if(!text||!onTasksChange)return;onTasksChange([...tasks,{id:crypto.randomUUID(),text,done:false,effort:"normal",projectId}]);setNewActions(s=>({...s,[projectId]:""}))};
 const patchAction=(id:string,patch:Partial<TaskItem>)=>onTasksChange?.(tasks.map(t=>t.id===id?{...t,...patch}:t));
 const toggleAction=(id:string)=>{const t=tasks.find(x=>x.id===id);if(t)patchAction(id,{done:!t.done,todayDate:t.done?t.todayDate:undefined,waiting:t.done?t.waiting:false})};
 const toggleWaiting=(id:string)=>{const t=tasks.find(x=>x.id===id);if(!t)return;patchAction(id,{waiting:!t.waiting,waitingSince:!t.waiting?localDateKey():undefined,todayDate:!t.waiting?undefined:t.todayDate});setMenu(null)};
 const setEffort=(id:string,effort:EffortLevel)=>{patchAction(id,{effort});setMenu(null)};
 const deleteAction=(id:string)=>{onTasksChange?.(tasks.filter(t=>t.id!==id));setMenu(null)};
 const reorder=(projectId:string,targetId:string)=>{if(!dragged||dragged===targetId||!onTasksChange)return;const pt=tasks.filter(t=>t.projectId===projectId),from=pt.findIndex(t=>t.id===dragged),to=pt.findIndex(t=>t.id===targetId);if(from<0||to<0)return;const r=[...pt],[m]=r.splice(from,1);r.splice(to,0,m);let i=0;onTasksChange(tasks.map(t=>t.projectId===projectId?r[i++]:t));setDragged(null)};
 const today=localDateKey();const sorted=[...projects].sort((a,b)=>a.done!==b.done?(a.done?1:-1):a.dueDate&&b.dueDate?a.dueDate.localeCompare(b.dueDate):a.dueDate?-1:b.dueDate?1:a.name.localeCompare(b.name,"fr"));
 return <div className="space-y-8">
  <div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-[.22em] text-muted">Pilotage</p><h2 className="font-display text-3xl mt-1" style={{color:accentColor}}>Projets</h2><p className="text-sm text-muted mt-2">La couleur identifie le grand projet sans envahir l’interface.</p></div><button onClick={()=>setCreating(v=>!v)} className="shrink-0 rounded-full border border-white/15 px-4 py-2 text-[11px] font-mono uppercase tracking-widest" style={{color:accentColor}}>{creating?"Fermer":"+ Nouveau"}</button></div>
  {creating&&<div className="rounded-2xl border border-white/10 bg-panel p-5 space-y-4" style={{boxShadow:`inset 3px 0 0 ${accentColor}`}}><p className="text-[10px] font-mono uppercase tracking-widest" style={{color:accentColor}}>Nouveau projet</p><div className="grid sm:grid-cols-2 gap-3"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Nom du projet" className="bg-graphite border border-white/10 rounded-lg px-4 py-3"/><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Résultat attendu" className="bg-graphite border border-white/10 rounded-lg px-4 py-3"/></div><div className="flex flex-col sm:flex-row gap-3"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="flex-1 bg-graphite border border-white/10 rounded-lg px-4 py-3 text-sm"/><button onClick={add} disabled={!name.trim()} className="rounded-lg px-5 py-3 font-mono text-xs uppercase text-graphite disabled:opacity-40" style={{backgroundColor:accentColor}}>Créer</button></div></div>}
  <div className="space-y-5">{projects.length===0&&<div className="rounded-2xl border border-white/10 border-dashed px-6 py-10 text-center"><p className="font-display text-xl" style={{color:accentColor}}>Aucun projet.</p></div>}{sorted.map(p=>{const linked=tasks.filter(t=>t.projectId===p.id),open=linked.filter(t=>!t.done),done=linked.filter(t=>t.done);return <article key={p.id} className={`rounded-2xl border border-white/10 bg-panel overflow-visible ${p.done?"opacity-60":""}`} style={{boxShadow:`inset 3px 0 0 ${accentColor}`}}>
   <div className="p-5 sm:p-6"><div className="flex items-start gap-4"><button onClick={()=>onChange(projects.map(x=>x.id===p.id?{...x,done:!x.done}:x))} className="mt-1 w-6 h-6 rounded-md border border-white/20 shrink-0 text-xs" style={p.done?{color:accentColor}: {color:"transparent"}}>✓</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:accentColor}}/><h3 className={`font-display text-2xl ${p.done?"line-through":""}`} style={{color:accentColor}}>{p.name}</h3></div>{p.goal&&<p className="text-sm text-muted mt-3">{p.goal}</p>}<div className="flex flex-wrap gap-2 mt-4"><span className="rounded-full border border-white/10 bg-graphite px-2.5 py-1 text-[10px] font-mono uppercase text-muted">{open.length} à faire</span>{done.length>0&&<span className="rounded-full border border-white/10 bg-graphite px-2.5 py-1 text-[10px] font-mono uppercase text-muted">{done.length} terminée{done.length>1?"s":""}</span>}{editingDate===p.id?<input autoFocus type="date" defaultValue={p.dueDate||""} onBlur={e=>{onChange(projects.map(x=>x.id===p.id?{...x,dueDate:e.target.value||undefined}:x));setEditingDate(null)}} className="bg-graphite rounded-full px-3 py-1 text-[10px] border border-white/10"/>:<button onClick={()=>setEditingDate(p.id)} className="rounded-full border border-white/10 bg-graphite px-2.5 py-1 text-[10px] font-mono uppercase text-muted">{p.dueDate?new Date(p.dueDate+"T00:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"short",year:"numeric"}):"+ échéance"}</button>}</div></div><div className="relative"><button onClick={()=>setMenu(menu===`p:${p.id}`?null:`p:${p.id}`)} className="px-2 py-1 text-muted">•••</button>{menu===`p:${p.id}`&&<div className="absolute right-0 top-8 z-20 w-40 rounded-lg border border-white/10 bg-graphite p-1 shadow-xl"><button onClick={()=>{onChange(projects.filter(x=>x.id!==p.id));setMenu(null)}} className="w-full px-3 py-2 text-left text-xs text-alert">Supprimer le projet</button></div>}</div></div></div>
   <div className="border-t border-white/10 px-5 sm:px-6 py-5 rounded-b-2xl bg-white/[.015]"><p className="text-[10px] font-mono uppercase tracking-[.18em] mb-3" style={{color:accentColor}}>Actions</p><div className="space-y-2">{open.length===0&&<p className="text-sm text-muted py-2">Aucune action ouverte.</p>}{open.map((t,i)=><div key={t.id} draggable onDragStart={()=>setDragged(t.id)} onDragEnd={()=>setDragged(null)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(p.id,t.id)} className="flex items-center gap-3 rounded-xl border border-white/10 bg-graphite/40 px-3 py-3.5" style={{boxShadow:`inset 2px 0 0 ${accentColor}`,opacity:t.waiting?.68:1}}><button onClick={()=>toggleAction(t.id)} className="w-5 h-5 rounded border border-white/20 text-transparent">✓</button><span className="font-mono text-[10px] text-muted">{String(i+1).padStart(2,"0")}</span><span className="h-2 w-2 rounded-full" style={{backgroundColor:accentColor}}/><span className="flex-1 text-sm">{t.text}</span><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-mono uppercase text-muted">{EFFORT_LABEL[t.effort??"normal"]}</span>{t.todayDate===today&&<span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-mono uppercase text-muted">Aujourd’hui</span>}{t.waiting&&<span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-mono uppercase text-muted">En attente</span>}{editingActionDate===t.id?<input autoFocus type="date" defaultValue={t.dueDate||""} onBlur={e=>{patchAction(t.id,{dueDate:e.target.value||undefined});setEditingActionDate(null)}} className="bg-graphite rounded-md px-2 py-1 text-[9px] border border-white/10"/>:t.dueDate&&<button onClick={()=>setEditingActionDate(t.id)} className="text-[9px] font-mono text-muted">{new Date(t.dueDate+"T00:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}</button>}<div className="relative"><button onClick={()=>setMenu(menu===`a:${t.id}`?null:`a:${t.id}`)} className="px-1.5 text-muted">•••</button>{menu===`a:${t.id}`&&<div className="absolute right-0 top-7 z-30 w-48 rounded-lg border border-white/10 bg-graphite p-1 shadow-xl"><p className="px-3 pt-2 pb-1 text-[9px] font-mono uppercase text-muted">Charge</p>{([['light','Basse'],['normal','Normale'],['heavy','Haute']] as const).map(([v,l])=><button key={v} onClick={()=>setEffort(t.id,v)} className="w-full px-3 py-1.5 text-left text-xs" style={(t.effort===v||(!t.effort&&v==='normal'))?{color:accentColor}:undefined}>{l}</button>)}<button onClick={()=>{setEditingActionDate(t.id);setMenu(null)}} className="w-full px-3 py-2 text-left text-xs text-muted">Échéance</button><button onClick={()=>toggleWaiting(t.id)} className="w-full px-3 py-2 text-left text-xs text-muted">{t.waiting?"Réactiver":"Mettre en attente"}</button><button onClick={()=>deleteAction(t.id)} className="w-full px-3 py-2 text-left text-xs text-alert">Supprimer</button></div>}</div></div></div>)}</div>
   {done.length>0&&<details className="mt-3"><summary className="cursor-pointer text-[10px] font-mono uppercase text-muted">{done.length} terminée{done.length>1?"s":""}</summary><div className="mt-2 space-y-1">{done.map(t=><div key={t.id} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-muted"><button onClick={()=>toggleAction(t.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span style={{color:accentColor}}>✓</span><span className="line-through flex-1 truncate">{t.text}</span><span className="text-[9px] font-mono uppercase">Réouvrir</span></button><button onClick={()=>deleteAction(t.id)} className="text-muted/30 hover:text-alert">×</button></div>)}</div></details>}
   {onTasksChange&&<div className="mt-4 flex gap-2"><input value={newActions[p.id]||""} onChange={e=>setNewActions(s=>({...s,[p.id]:e.target.value}))} onKeyDown={e=>e.key==="Enter"&&addAction(p.id)} placeholder="Ajouter une action…" className="min-w-0 flex-1 bg-transparent border-b border-white/10 px-1 py-2 text-sm outline-none"/><button onClick={()=>addAction(p.id)} disabled={!(newActions[p.id]||"").trim()} className="text-[10px] font-mono uppercase tracking-widest disabled:opacity-30" style={{color:accentColor}}>Ajouter</button></div>}
   </div></article>})}</div>
 </div>
}
