"use client";
import { useState } from "react";
import { Project, TaskItem } from "@/lib/storage";
export default function TaskPanel({items,onChange,maxOpenTasks,projects=[]}:{items:TaskItem[];onChange:(items:TaskItem[])=>void;maxOpenTasks?:number;projects?:Project[]}){
 const[text,setText]=useState(""); const[projectId,setProjectId]=useState(""); const openCount=items.filter(t=>!t.done).length; const limitReached=typeof maxOpenTasks==="number"&&openCount>=maxOpenTasks;
 const addTask=()=>{const value=text.trim();if(!value||limitReached)return;onChange([...items,{id:crypto.randomUUID(),text:value,done:false,projectId:projectId||undefined}]);setText("");setProjectId("");};
 const toggle=(id:string)=>onChange(items.map(t=>t.id===id?{...t,done:!t.done}:t)); const remove=(id:string)=>onChange(items.filter(t=>t.id!==id)); const todo=items.filter(t=>!t.done),done=items.filter(t=>t.done);
 const row=(t:TaskItem,isDone:boolean)=><label key={t.id} className={`group flex items-center gap-3 border rounded-md px-3 py-2.5 cursor-pointer ${isDone?"bg-panel/60 border-white/5":"bg-panel border-white/10"}`}><input type="checkbox" checked={t.done} onChange={()=>toggle(t.id)} className={`w-4 h-4 shrink-0 ${isDone?"accent-teal":"accent-amber"}`}/><div className="flex-1 min-w-0"><span className={`text-sm ${isDone?"text-muted line-through":""}`}>{t.text}</span><div className="flex gap-2 mt-1">{t.carried&&!isDone&&<span className="font-mono text-[9px] uppercase tracking-widest text-alert">reportée</span>}{t.projectId&&<span className="font-mono text-[9px] uppercase tracking-widest text-muted">{projects.find(p=>p.id===t.projectId)?.name??"projet"}</span>}</div></div><button onClick={e=>{e.preventDefault();remove(t.id)}} className="text-muted hover:text-alert text-xs p-2 -m-2 sm:opacity-0 sm:group-hover:opacity-100">✕</button></label>;
 return <div className="space-y-8"><div className="space-y-2"><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addTask()}} disabled={limitReached} placeholder={limitReached?"Limite du mode rouge atteinte":"Nouvelle tâche"} className="flex-1 min-w-0 bg-panel border border-white/10 rounded-md px-3 py-2.5 disabled:opacity-50"/><button onClick={addTask} disabled={limitReached} className="font-mono text-xs uppercase tracking-widest px-4 py-2 rounded-md bg-amber text-graphite disabled:opacity-40">Ajouter</button></div>{projects.filter(p=>!p.done).length>0&&<select value={projectId} onChange={e=>setProjectId(e.target.value)} className="w-full bg-panel border border-white/10 rounded-md px-3 py-2 text-xs text-muted"><option value="">Aucun projet lié</option>{projects.filter(p=>!p.done).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}{typeof maxOpenTasks==="number"&&<p className="text-xs text-alert font-mono uppercase tracking-widest">Mode rouge — {openCount}/{maxOpenTasks} tâches actives maximum</p>}</div>{todo.length===0&&done.length===0&&<p className="text-sm text-muted">Aucune tâche pour l'instant.</p>}{todo.length>0&&<div className="space-y-2">{todo.map(t=>row(t,false))}</div>}{done.length>0&&<div className="space-y-2"><span className="block text-xs font-mono uppercase tracking-widest text-muted">Fait ({done.length})</span>{done.map(t=>row(t,true))}</div>}</div>;
}
