export type Domain = "musique" | "esport" | "vie";
export type CapacityLevel = "low" | "normal" | "high";
export type EffortLevel = "light" | "normal" | "heavy";
export type TaskItem = { id: string; text: string; done: boolean; dueDate?: string; projectId?: string; carried?: boolean; effort?:EffortLevel; waiting?:boolean; waitingSince?:string };
export type Project = { id: string; name: string; goal: string; dueDate?: string; done: boolean };
export type BriefingData = { date: string; p1: string; p2: string; p3: string; p1Done: boolean; p2Done: boolean; p3Done: boolean; p1Effort?:EffortLevel; p2Effort?:EffortLevel; p3Effort?:EffortLevel; bonus: string; skip: string; tasks: TaskItem[] };
export type DumpCategory = "URGENT" | "PLANIFIER" | "PARKING" | "OUBLIE" | null;
export type DumpItem = { id: string; text: string; category: DumpCategory };
export type ReviewDraft = { advanced: string; notDone: string; why: string; keep: string; change: string; next1: string; next2: string; next3: string };
export type ReviewEntry = ReviewDraft & { id: string; savedAt: string; tasksDoneCount?: number; prioritiesDoneCount?: number };
export type CompletedTask = { id: string; text: string; date: string; kind?: "priority" | "task"; priorityRank?: 1 | 2 | 3 };
export type DomainState = { briefing: BriefingData; dump: DumpItem[]; projects: Project[]; completedThisWeek: CompletedTask[]; reviewDraft: ReviewDraft; reviewHistory: ReviewEntry[] };
export type LoadSettings = { lowCapacity:number; normalCapacity:number; highCapacity:number; priorityWeight:number; taskWeight:number; urgentWeight:number; dueWeight:number };
export type DailyCapacity = { date:string; level:CapacityLevel };
export type LoadHistoryEntry={date:string;capacity:CapacityLevel|null;plannedPoints:number;peakPlannedPoints:number;completedPoints:number;completedPriorities:number;completedTasks:number;carriedTasks:number;updatedAt:string};
export type LoadInsight={level:CapacityLevel;sampleSize:number;configured:number;averagePlanned:number;averageCompleted:number;completionRate:number;suggested:number;direction:"lower"|"higher";signature:string};
export const DEFAULT_LOAD_SETTINGS:LoadSettings={lowCapacity:60,normalCapacity:100,highCapacity:140,priorityWeight:20,taskWeight:8,urgentWeight:12,dueWeight:15};
export function effortMultiplier(e:EffortLevel|undefined){return e==="light"?.6:e==="heavy"?1.5:1;}
export function localDateKey(date = new Date()): string { const y=date.getFullYear(); const m=String(date.getMonth()+1).padStart(2,"0"); const d=String(date.getDate()).padStart(2,"0"); return `${y}-${m}-${d}`; }
function startOfCurrentWeek(): string { const date=new Date(); const day=date.getDay(); date.setHours(0,0,0,0); date.setDate(date.getDate()+(day===0?-6:1-day)); return localDateKey(date); }
function keepCurrentWeek(tasks: CompletedTask[]): CompletedTask[] { const monday=startOfCurrentWeek(), today=localDateKey(); return tasks.filter(t=>t.date>=monday&&t.date<=today); }
export const emptyBriefing=():BriefingData=>({date:localDateKey(),p1:"",p2:"",p3:"",p1Done:false,p2Done:false,p3Done:false,p1Effort:"normal",p2Effort:"normal",p3Effort:"normal",bonus:"",skip:"",tasks:[]});
export const emptyReviewDraft=():ReviewDraft=>({advanced:"",notDone:"",why:"",keep:"",change:"",next1:"",next2:"",next3:""});
export const defaultDomainState=():DomainState=>({briefing:emptyBriefing(),dump:[],projects:[],completedThisWeek:[],reviewDraft:emptyReviewDraft(),reviewHistory:[]});
function priorityRows(b:BriefingData){return ([1,2,3] as const).map(rank=>({text:b[`p${rank}` as "p1"|"p2"|"p3"],done:b[`p${rank}Done` as "p1Done"|"p2Done"|"p3Done"],effort:b[`p${rank}Effort` as "p1Effort"|"p2Effort"|"p3Effort"]})).filter(p=>p.text.trim());}
export function waitingNeedsAttention(task:TaskItem,projects:Project[]){if(!task.waiting||!task.projectId)return false;const p=projects.find(x=>x.id===task.projectId);if(!p?.dueDate||p.done)return false;const today=new Date(localDateKey()+"T00:00:00"),due=new Date(p.dueDate+"T00:00:00");return Math.ceil((due.getTime()-today.getTime())/86400000)<=2;}
export function rawWorkload(state:DomainState,settings:LoadSettings):number{const priorities=priorityRows(state.briefing).filter(p=>!p.done).reduce((n,p)=>n+settings.priorityWeight*effortMultiplier(p.effort),0);const tasks=state.briefing.tasks.filter(t=>!t.done&&!t.waiting).reduce((n,t)=>n+settings.taskWeight*effortMultiplier(t.effort),0);const urgent=state.dump.filter(i=>i.category==="URGENT").length*settings.urgentWeight;const today=localDateKey();const due=state.projects.filter(p=>!p.done&&p.dueDate&&p.dueDate<=today).length*settings.dueWeight;return Math.round(priorities+tasks+urgent+due);}
export function workloadBreakdown(state:DomainState,settings:LoadSettings){const ps=priorityRows(state.briefing).filter(p=>!p.done);const ts=state.briefing.tasks.filter(t=>!t.done&&!t.waiting);const urgent=state.dump.filter(i=>i.category==="URGENT").length;const today=localDateKey();const due=state.projects.filter(p=>!p.done&&p.dueDate&&p.dueDate<=today).length;return {priorities:ps.length,tasks:ts.length,urgent,due,priorityPoints:Math.round(ps.reduce((n,p)=>n+settings.priorityWeight*effortMultiplier(p.effort),0)),taskPoints:Math.round(ts.reduce((n,t)=>n+settings.taskWeight*effortMultiplier(t.effort),0)),urgentPoints:urgent*settings.urgentWeight,duePoints:due*settings.dueWeight};}
export function capacityValue(level:CapacityLevel,settings:LoadSettings){return level==="low"?settings.lowCapacity:level==="high"?settings.highCapacity:settings.normalCapacity;}
export function workloadUsage(state:DomainState,settings:LoadSettings,level:CapacityLevel){const raw=rawWorkload(state,settings);const capacity=capacityValue(level,settings);return {raw,capacity,percent:capacity>0?Math.round(raw/capacity*100):0};}
export function syncWeeklyCompletedTasks(log:CompletedTask[],briefing:BriefingData):CompletedTask[]{const current=keepCurrentWeek(log).map(e=>({...e,kind:e.kind??"task" as const}));const taskIds=new Set(briefing.tasks.map(t=>t.id));const priorityIds=new Set([1,2,3].map(rank=>`priority:${briefing.date}:${rank}`));const kept=current.filter(e=>{if(e.kind==="priority"&&priorityIds.has(e.id)){const rank=e.priorityRank??Number(e.id.split(":").pop()) as 1|2|3;return Boolean(briefing[`p${rank}Done` as "p1Done"|"p2Done"|"p3Done"]);}if(e.kind!=="priority"&&taskIds.has(e.id))return briefing.tasks.find(t=>t.id===e.id)?.done??false;return true;});const existing=new Set(kept.map(e=>e.id));const taskAdditions=briefing.tasks.filter(t=>t.done&&!existing.has(t.id)).map(t=>({id:t.id,text:t.text,date:briefing.date,kind:"task" as const}));const priorityAdditions=([1,2,3] as const).flatMap(rank=>{const text=briefing[`p${rank}` as "p1"|"p2"|"p3"].trim();const done=briefing[`p${rank}Done` as "p1Done"|"p2Done"|"p3Done"];const id=`priority:${briefing.date}:${rank}`;return done&&text&&!existing.has(id)?[{id,text,date:briefing.date,kind:"priority" as const,priorityRank:rank}]:[];});return [...kept,...priorityAdditions,...taskAdditions];}
function domainKey(domain:Domain){return `ibes:${domain}`;}
function parseDomainState(domain:Domain):DomainState{try{const raw=window.localStorage.getItem(domainKey(domain));if(!raw)return defaultDomainState();const parsed=JSON.parse(raw);return {...defaultDomainState(),...parsed,briefing:{...emptyBriefing(),...parsed.briefing},projects:parsed.projects??[]};}catch{return defaultDomainState();}}
const MODE_ROUGE_KEY="ibes:mode-rouge",LOAD_SETTINGS_KEY="ibes:load-settings",DAILY_CAPACITY_KEY="ibes:daily-capacity",LOAD_HISTORY_KEY="ibes:load-history",INSIGHT_DISMISS_KEY="ibes:load-insight-dismissed";
function recordLoadHistory(){if(typeof window==="undefined")return;const settings=loadLoadSettings();const states=(['musique','esport','vie'] as Domain[]).map(parseDomainState);const date=localDateKey();const capacity=loadDailyCapacity()?.level??null;const plannedPoints=states.reduce((n,s)=>n+rawWorkload(s,settings),0);let completedPoints=0,completedPriorities=0,completedTasks=0,carriedTasks=0;for(const s of states){for(const p of priorityRows(s.briefing)){if(p.done){completedPriorities++;completedPoints+=settings.priorityWeight*effortMultiplier(p.effort);}}for(const t of s.briefing.tasks){if(t.done){completedTasks++;completedPoints+=settings.taskWeight*effortMultiplier(t.effort);}if(t.carried&&!t.done&&!t.waiting)carriedTasks++;}}try{const history:LoadHistoryEntry[]=JSON.parse(window.localStorage.getItem(LOAD_HISTORY_KEY)||'[]');const old=history.find(h=>h.date===date);const entry:LoadHistoryEntry={date,capacity,plannedPoints,peakPlannedPoints:Math.max(old?.peakPlannedPoints??0,plannedPoints+Math.round(completedPoints)),completedPoints:Math.round(completedPoints),completedPriorities,completedTasks,carriedTasks,updatedAt:new Date().toISOString()};const next=[...history.filter(h=>h.date!==date),entry].sort((a,b)=>a.date.localeCompare(b.date)).slice(-90);window.localStorage.setItem(LOAD_HISTORY_KEY,JSON.stringify(next));}catch{}}
export function loadLoadHistory():LoadHistoryEntry[]{if(typeof window==="undefined")return[];try{return JSON.parse(window.localStorage.getItem(LOAD_HISTORY_KEY)||'[]');}catch{return[];}}
export function getLoadInsight(settings:LoadSettings):LoadInsight|null{if(typeof window==="undefined")return null;const history=loadLoadHistory().filter(h=>h.capacity&&h.date<localDateKey()&&h.peakPlannedPoints>0);const levels:CapacityLevel[]=["normal","low","high"];for(const level of levels){const rows=history.filter(h=>h.capacity===level);if(rows.length<7)continue;const recent=rows.slice(-14);const avgPlanned=Math.round(recent.reduce((n,h)=>n+h.peakPlannedPoints,0)/recent.length);const avgCompleted=Math.round(recent.reduce((n,h)=>n+h.completedPoints,0)/recent.length);const completionRate=avgPlanned?Math.round(avgCompleted/avgPlanned*100):0;const configured=capacityValue(level,settings);let direction:"lower"|"higher"|null=null;let suggested=configured;if(completionRate<75&&avgPlanned>=configured*.7){direction="lower";suggested=Math.max(20,Math.round(avgCompleted/5)*5);}else if(completionRate>=90&&avgPlanned>=configured*.9&&avgCompleted>=configured*.9){direction="higher";suggested=Math.round(Math.max(configured*1.1,avgCompleted*1.1)/5)*5;}if(!direction||Math.abs(suggested-configured)<10)continue;const signature=`${level}:${rows.length}:${direction}:${suggested}`;let dismissed="";try{dismissed=window.localStorage.getItem(INSIGHT_DISMISS_KEY)||"";}catch{}if(dismissed===signature)continue;return{level,sampleSize:recent.length,configured,averagePlanned:avgPlanned,averageCompleted:avgCompleted,completionRate,suggested,direction,signature};}return null;}
export function dismissLoadInsight(signature:string){if(typeof window!=="undefined")window.localStorage.setItem(INSIGHT_DISMISS_KEY,signature);}
export function loadDomainState(domain:Domain):DomainState{if(typeof window==="undefined")return defaultDomainState();try{const state=parseDomainState(domain);state.completedThisWeek=keepCurrentWeek(state.completedThisWeek??[]);if(state.briefing.date!==localDateKey()){const unfinished=(state.briefing.tasks??[]).filter((t:TaskItem)=>!t.done).map((t:TaskItem)=>({...t,carried:t.waiting?t.carried:true}));state.briefing={...emptyBriefing(),tasks:unfinished};window.localStorage.setItem(domainKey(domain),JSON.stringify(state));}return state;}catch{return defaultDomainState();}}
export function saveDomainState(domain:Domain,state:DomainState){if(typeof window!=="undefined"){window.localStorage.setItem(domainKey(domain),JSON.stringify(state));recordLoadHistory();}}
export function loadModeRouge():boolean{return typeof window!=="undefined"&&window.localStorage.getItem(MODE_ROUGE_KEY)==="1";}export function saveModeRouge(active:boolean){if(typeof window!=="undefined")window.localStorage.setItem(MODE_ROUGE_KEY,active?"1":"0");}
export function loadLoadSettings():LoadSettings{if(typeof window==="undefined")return DEFAULT_LOAD_SETTINGS;try{return {...DEFAULT_LOAD_SETTINGS,...JSON.parse(window.localStorage.getItem(LOAD_SETTINGS_KEY)||"{}")};}catch{return DEFAULT_LOAD_SETTINGS;}}export function saveLoadSettings(settings:LoadSettings){if(typeof window!=="undefined"){window.localStorage.setItem(LOAD_SETTINGS_KEY,JSON.stringify(settings));recordLoadHistory();}}
export function loadDailyCapacity():DailyCapacity|null{if(typeof window==="undefined")return null;try{const parsed=JSON.parse(window.localStorage.getItem(DAILY_CAPACITY_KEY)||"null");return parsed?.date===localDateKey()?parsed:null;}catch{return null;}}export function saveDailyCapacity(level:CapacityLevel){if(typeof window!=="undefined"){window.localStorage.setItem(DAILY_CAPACITY_KEY,JSON.stringify({date:localDateKey(),level}));recordLoadHistory();}}
