"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {loadCustomWorkspaces,loadDomainState,loadLoadHistory,ReviewEntry} from "@/lib/storage";

type Row={project:string;color:string;entry:ReviewEntry};
export default function HistoryPage(){
 const[rows,setRows]=useState<Row[]>([]);const[activity,setActivity]=useState<ReturnType<typeof loadLoadHistory>>([]);const[view,setView]=useState<"semaines"|"mois"|"activite">("semaines");
 useEffect(()=>{const fixed=[{project:"Musique",color:"text-amber",history:loadDomainState("musique").reviewHistory},{project:"Esport",color:"text-cyan",history:loadDomainState("esport").reviewHistory}];const custom=loadCustomWorkspaces().map(w=>({project:w.name,color:"text-teal",history:w.state.reviewHistory}));setRows([...fixed,...custom].flatMap(x=>x.history.map(entry=>({project:x.project,color:x.color,entry}))).sort((a,b)=>b.entry.savedAt.localeCompare(a.entry.savedAt)));setActivity(loadLoadHistory().slice().reverse())},[]);
 const months=useMemo(()=>{const map=new Map<string,Row[]>();rows.forEach(r=>{const d=new Date(r.entry.savedAt),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;map.set(key,[...(map.get(key)||[]),r])});return[...map.entries()].sort((a,b)=>b[0].localeCompare(a[0]))},[rows]);
 return <main className="min-h-screen px-6 py-8 max-w-4xl mx-auto"><header className="flex items-center justify-between gap-4 mb-9"><div><h1 className="font-display text-3xl">Historique</h1><p className="text-xs font-mono uppercase tracking-widest text-muted">la mémoire d'IBES</p></div><Link href="/" className="text-xs font-mono uppercase tracking-widest text-muted">← Cockpit</Link></header><nav className="flex gap-1 border-b border-white/10 mb-8">{([['semaines','Semaines'],['mois','Mois'],['activite','Activité']] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`px-4 py-3 text-xs font-mono uppercase tracking-widest border-b-2 ${view===id?'border-teal text-ink':'border-transparent text-muted'}`}>{label}</button>)}</nav>
 {view==="semaines"&&<div className="space-y-3">{rows.length===0?<p className="text-muted">Ton premier bilan apparaîtra ici.</p>:rows.map(r=><details key={r.entry.id} className="bg-panel border border-white/10 rounded-xl p-4"><summary className="cursor-pointer flex justify-between gap-4"><span><span className={`font-display ${r.color}`}>{r.project}</span><span className="text-sm text-muted ml-3">{new Date(r.entry.savedAt).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</span></span><span className="text-xs text-muted">{r.entry.prioritiesDoneCount??0} priorités</span></summary><div className="mt-4 pt-4 border-t border-white/10 space-y-2 text-sm"><p><span className="text-muted">Avancé — </span>{r.entry.advanced||'—'}</p><p><span className="text-muted">Freins — </span>{r.entry.why||'—'}</p><p><span className="text-muted">À garder — </span>{r.entry.keep||'—'}</p><p><span className="text-muted">À modifier — </span>{r.entry.change||'—'}</p><p><span className="text-muted">Suite — </span>{[r.entry.next1,r.entry.next2,r.entry.next3].filter(Boolean).join(' · ')||'—'}</p></div></details>)}</div>}
 {view==="mois"&&<div className="space-y-5">{months.length===0?<p className="text-muted">Les rétrospectives mensuelles se construiront à partir de tes bilans.</p>:months.map(([key,items])=>{const date=new Date(key+'-01T00:00:00'),done=items.reduce((n,r)=>n+(r.entry.prioritiesDoneCount??0),0);return <section key={key} className="bg-panel border border-white/10 rounded-2xl p-6"><p className="text-[10px] font-mono uppercase tracking-widest text-muted">Rétrospective</p><h2 className="font-display text-3xl mt-1 capitalize">{date.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><div className="font-display text-4xl text-teal mt-6">{done}</div><p className="text-xs text-muted">priorités terminées dans les bilans enregistrés</p><div className="mt-6 space-y-2">{items.map(r=><div key={r.entry.id} className="flex justify-between border-t border-white/10 pt-2 text-sm"><span className={r.color}>{r.project}</span><span className="text-muted">{r.entry.prioritiesDoneCount??0} priorités</span></div>)}</div></section>})}</div>}
 {view==="activite"&&<div className="space-y-2">{activity.length===0?<p className="text-muted">L'activité apparaîtra ici au fil de ton utilisation.</p>:activity.map(a=><div key={a.date} className="bg-panel border border-white/10 rounded-lg px-4 py-3 flex justify-between gap-4"><div><p className="text-sm">{new Date(a.date+'T00:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})}</p><p className="text-[10px] font-mono uppercase text-muted">{a.capacity?`capacité ${a.capacity}`:'capacité non renseignée'}</p></div><div className="text-right"><p className="font-mono text-sm">{a.completedPoints} pts absorbés</p><p className="text-[10px] text-muted">{a.completedPriorities} priorités terminées</p></div></div>)}</div>}
 </main>;
}
