"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {loadCustomWorkspaces,loadDomainState,loadLoadHistory,ReviewEntry} from "@/lib/storage";

type Row={project:string;color:string;entry:ReviewEntry};
const WEEK_KEY="ibes:review-week-seen";
function localKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function mondayOf(d:Date){const x=new Date(d);x.setHours(0,0,0,0);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x}
function targetWeek(d=new Date()){const x=new Date(d),day=x.getDay(),after18=x.getHours()>=18;const start=mondayOf(x);if(day!==0||!after18)start.setDate(start.getDate()-7);const end=new Date(start);end.setDate(end.getDate()+6);return{start,end,key:localKey(start)}}
function shortDate(d:Date){return d.toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}

export default function HistoryPage(){
 const[rows,setRows]=useState<Row[]>([]);const[activity,setActivity]=useState<ReturnType<typeof loadLoadHistory>>([]);const[view,setView]=useState<"semaines"|"mois"|"activite">("semaines");const[weeklyOpen,setWeeklyOpen]=useState(false);const[weekDone,setWeekDone]=useState(false);
 useEffect(()=>{const fixed=[{project:"Musique",color:"text-amber",history:loadDomainState("musique").reviewHistory},{project:"Esport",color:"text-cyan",history:loadDomainState("esport").reviewHistory}];const custom=loadCustomWorkspaces().map(w=>({project:w.name,color:"text-teal",history:w.state.reviewHistory}));setRows([...fixed,...custom].flatMap(x=>x.history.map(entry=>({project:x.project,color:x.color,entry}))).sort((a,b)=>b.entry.savedAt.localeCompare(a.entry.savedAt)));setActivity(loadLoadHistory().slice().reverse());setWeeklyOpen(new URLSearchParams(window.location.search).get("bilan")==="semaine");const wk=targetWeek();setWeekDone(localStorage.getItem(WEEK_KEY)===wk.key)},[]);
 const months=useMemo(()=>{const map=new Map<string,Row[]>();rows.forEach(r=>{const d=new Date(r.entry.savedAt),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;map.set(key,[...(map.get(key)||[]),r])});return[...map.entries()].sort((a,b)=>b[0].localeCompare(a[0]))},[rows]);
 const week=targetWeek();const weekRows=activity.filter(a=>a.date>=localKey(week.start)&&a.date<=localKey(week.end)).slice().reverse();const totalPriorities=weekRows.reduce((n,a)=>n+a.completedPriorities,0);const totalCompleted=weekRows.reduce((n,a)=>n+a.completedPoints,0);const totalPeak=weekRows.reduce((n,a)=>n+a.peakPlannedPoints,0);
 const markWeekDone=()=>{localStorage.setItem(WEEK_KEY,week.key);setWeekDone(true)};
 return <main className="min-h-screen px-6 py-8 max-w-4xl mx-auto"><header className="flex items-center justify-between gap-4 mb-9"><div><h1 className="font-display text-3xl">Historique</h1><p className="text-xs font-mono uppercase tracking-widest text-muted">la mémoire d&apos;IBES</p></div><Link href="/" className="text-xs font-mono uppercase tracking-widest text-muted">← Cockpit</Link></header>
 {weeklyOpen&&<section className="mb-10 rounded-2xl border border-teal/30 bg-teal/5 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-widest text-teal">Bilan de semaine</p><h2 className="font-display text-3xl mt-1">{shortDate(week.start)} → {shortDate(week.end)}</h2><p className="text-sm text-muted mt-2">IBES a rassemblé les journées enregistrées sur cette période.</p></div>{weekDone&&<span className="text-xs font-mono uppercase tracking-widest text-teal">✓ bilan validé</span>}</div><div className="grid sm:grid-cols-3 gap-3 mt-6"><div className="bg-panel border border-white/10 rounded-lg p-4"><div className="font-display text-3xl text-teal">{totalPriorities}</div><div className="text-[10px] font-mono uppercase tracking-widest text-muted">priorités terminées</div></div><div className="bg-panel border border-white/10 rounded-lg p-4"><div className="font-display text-3xl text-amber">{Math.round(totalCompleted*10)/10}</div><div className="text-[10px] font-mono uppercase tracking-widest text-muted">charge absorbée</div></div><div className="bg-panel border border-white/10 rounded-lg p-4"><div className="font-display text-3xl">{weekRows.length}</div><div className="text-[10px] font-mono uppercase tracking-widest text-muted">journées enregistrées</div></div></div>{weekRows.length>0?<div className="mt-6 space-y-2">{weekRows.map(a=><div key={a.date} className="bg-panel border border-white/10 rounded-lg px-4 py-3 flex justify-between gap-4"><div><p className="text-sm capitalize">{new Date(a.date+"T00:00:00").toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"short"})}</p><p className="text-[10px] font-mono uppercase text-muted">{a.capacity?`capacité ${a.capacity}`:"capacité non renseignée"}</p></div><div className="text-right"><p className="font-mono text-sm">{a.completedPriorities} priorité{a.completedPriorities!==1?"s":""}</p><p className="text-[10px] text-muted">{Math.round(a.completedPoints*10)/10} absorbés · pic {Math.round(a.peakPlannedPoints*10)/10}</p></div></div>)}</div>:<p className="text-sm text-muted mt-6">Aucune journée n’a été enregistrée sur cette semaine.</p>}<p className="mt-5 text-xs text-muted">Pic de charge cumulé enregistré : {Math.round(totalPeak*10)/10}. Les anciennes versions d’IBES ne conservaient pas encore le nom de chaque tâche après le changement de semaine ; les prochains bilans garderont ce détail.</p>{!weekDone&&<button onClick={markWeekDone} className="mt-5 rounded-md bg-teal px-4 py-2 font-mono text-xs uppercase tracking-widest text-graphite">J’ai fait mon bilan</button>}</section>}
 <nav className="flex gap-1 border-b border-white/10 mb-8">{([['semaines','Semaines'],['mois','Mois'],['activite','Activité']] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`px-4 py-3 text-xs font-mono uppercase tracking-widest border-b-2 ${view===id?'border-teal text-ink':'border-transparent text-muted'}`}>{label}</button>)}</nav>
 {view==="semaines"&&<div className="space-y-3">{rows.length===0?<p className="text-muted">Ton premier bilan apparaîtra ici.</p>:rows.map(r=><details key={r.entry.id} className="bg-panel border border-white/10 rounded-xl p-4"><summary className="cursor-pointer flex justify-between gap-4"><span><span className={`font-display ${r.color}`}>{r.project}</span><span className="text-sm text-muted ml-3">{new Date(r.entry.savedAt).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</span></span><span className="text-xs text-muted">{r.entry.prioritiesDoneCount??0} priorités</span></summary><div className="mt-4 pt-4 border-t border-white/10 space-y-2 text-sm"><p><span className="text-muted">Avancé — </span>{r.entry.advanced||'—'}</p><p><span className="text-muted">Freins — </span>{r.entry.why||'—'}</p><p><span className="text-muted">À garder — </span>{r.entry.keep||'—'}</p><p><span className="text-muted">À modifier — </span>{r.entry.change||'—'}</p><p><span className="text-muted">Suite — </span>{[r.entry.next1,r.entry.next2,r.entry.next3].filter(Boolean).join(' · ')||'—'}</p></div></details>)}</div>}
 {view==="mois"&&<div className="space-y-5">{months.length===0?<p className="text-muted">Les rétrospectives mensuelles se construiront à partir de tes bilans.</p>:months.map(([key,items])=>{const date=new Date(key+'-01T00:00:00'),done=items.reduce((n,r)=>n+(r.entry.prioritiesDoneCount??0),0);return <section key={key} className="bg-panel border border-white/10 rounded-2xl p-6"><p className="text-[10px] font-mono uppercase tracking-widest text-muted">Rétrospective</p><h2 className="font-display text-3xl mt-1 capitalize">{date.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><div className="font-display text-4xl text-teal mt-6">{done}</div><p className="text-xs text-muted">priorités terminées dans les bilans enregistrés</p><div className="mt-6 space-y-2">{items.map(r=><div key={r.entry.id} className="flex justify-between border-t border-white/10 pt-2 text-sm"><span className={r.color}>{r.project}</span><span className="text-muted">{r.entry.prioritiesDoneCount??0} priorités</span></div>)}</div></section>})}</div>}
 {view==="activite"&&<div className="space-y-2">{activity.length===0?<p className="text-muted">L&apos;activité apparaîtra ici au fil de ton utilisation.</p>:activity.map(a=><div key={a.date} className="bg-panel border border-white/10 rounded-lg px-4 py-3 flex justify-between gap-4"><div><p className="text-sm">{new Date(a.date+'T00:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})}</p><p className="text-[10px] font-mono uppercase text-muted">{a.capacity?`capacité ${a.capacity}`:'capacité non renseignée'}</p></div><div className="text-right"><p className="font-mono text-sm">{a.completedPoints} pts absorbés</p><p className="text-[10px] text-muted">{a.completedPriorities} priorités terminées</p></div></div>)}</div>}
 </main>;
}
